### ISSUE TITLE
stringprintf.cc: needs #include <cstdio>

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waqasbhatti/wcs2kml#1]
```
What steps will reproduce the problem?
1. (try to) build on ubuntu 10.04 (lucid)

What is the expected output?
clean build

What do you see instead?
 g++ -DHAVE_CONFIG_H -I. -I../../src -I../../src -I../../src/google -I../../src/google/libwcs -I/usr/local/gflags-1.3//include -D_BSD_SOURCE -I/usr/local/gflags-1.3//include -g -O2 -I/usr/local/gflags-1.3//include -Wall -MT stringprintf.lo -MD -MP -MF .deps/stringprintf.Tpo -c stringprintf.cc  -fPIC -DPIC -o .libs/stringprintf.o
stringprintf.cc: In function 'void google_sky::StringPrintf(std::string*, int, 
const char*, ...)':
stringprintf.cc:39: error: 'vsnprintf' was not declared in this scope
stringprintf.cc: In function 'void google_sky::StringAppendF(std::string*, int, 
const char*, ...)':
stringprintf.cc:52: error: 'vsnprintf' was not declared in this scope
make[4]: *** [stringprintf.lo] Error 1


What version of the product are you using? On what operating system?
0.2.1

Please provide any additional information below.

Adding #include <cstdio> to stringprintf.cc fixes it.

```

Original issue reported on code.google.com by `dstnd...@gmail.com` on 26 Aug 2010 at 1:26
